### ISSUE TITLE
Download customised genomes / sequences via a list of species 

### ISSUE THREAD

**Issue by steffie11** [chassenr/taxdb-integration#3]
Dear developers,

I have read that in your `collect module`, genomes from various sources will be downloaded. Is it possible to specifiy a list of species to download? For example, a list contains species names of 200 mammals? 

Thanks a lot for the help.

Cheers,
Huang

**Comment by chassenr** [comment]
Dear Huang,

the workflow for the ```collect module``` was designed to automatically harvest available genomes from public databases (mainly NCBI refseq + genbank, GTDB, CheckV), and to filter those genomes so that the known diversity is evenly represented across lineages (and not dominanted my genomes from model organsisms). This process is not targeted as specific species. If you already know the species that you want to retrieve the genomes for, I would argue that there are easier ways to achieve this than to coerce the ```collect module``` into that purpose. 

There may, however, be elements in the ```collect module``` that you could recycle to fit your needs. E.g. You can use the assembly_summary files from refseq and genbank to obtain a list of all available genomes, with information about the assembly status (e.g. contig, scaffold, chromosome, complete genome), the genome representation (partial vs. full), the taxid, and the ftp download link. Based on the taxid you can then select the download links for all genomes for the 200 mammal species that you are interested in. Is this more or less what you are looking for? Let me know if you have further questions.

Below are the download links for the assembly_summary files:
```
wget https://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt
wget https://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt
```

To work with taxids I can highly recommend the [taxonkit](https://bioinf.shenwei.me/taxonkit/usage) package.

**Comment by steffie11** [comment]
Thanks a lot. I see. Actually I have done more or less similar as you recommended. Now I am convinced that I have done the corrent thing. 
I will write again if I have further questions.
